name: danmaku-server
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: danmaku-napcat
    env_file:
      - .env
    environment:
      - WSR_ENABLE=true
      - WS_URLS=["ws://danmaku-server:5098/onebot"]
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
    volumes:
      - ./napcat/config:/app/napcat/config
      - ./napcat/data:/app/.config/QQ
      - ./napcat/logs:/app/napcat/logs
    # ports:
    #   - 6099:6099
    restart: always
    depends_on:
      - danmaku-server

  danmaku-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danmaku-server
    env_file:
      - .env
    ports:
      - 5098:5098
    volumes:
      - ./config:/etc/danmaku-server
    restart: always
